//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckChanges.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class About_partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public About_partner()
        {
            this.Inventions = new HashSet<Inventions>();
            this.TrademarksIndex = new HashSet<TrademarksIndex>();
        }
    
        public int Attorney_ID { get; set; }
        public string Firm_ID { get; set; }
        public string Attorney_s_surname { get; set; }
        public string Attorney_s_names { get; set; }
        public string Prefix { get; set; }
        public string Occupation { get; set; }
        public bool Russian { get; set; }
        public string CreatorDate { get; set; }
        public string FirmID_save { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Special_instructions_ContactPerson { get; set; }
        public string Special_instructions_for_DN_ContactPerson { get; set; }
        public string BillingName { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCountry { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<int> LastUser { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> PartnerIDAPAF { get; set; }
        public Nullable<int> PartnerIdPCCP { get; set; }
        public Nullable<int> PartnerIdE { get; set; }
        public string PartnerDescription { get; set; }
        public Nullable<bool> PartnerIsPersonal { get; set; }
        public Nullable<bool> PartnerIsBefore { get; set; }
        public Nullable<bool> PartnerThroughTheIntermediary { get; set; }
        public Nullable<int> PartnerCreator { get; set; }
        public Nullable<System.DateTime> PartnerCreationDate { get; set; }
        public bool NotWrite { get; set; }
        public Nullable<bool> SendNotiftoTelegram { get; set; }
        public Nullable<bool> SendNotiftoViber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventions> Inventions { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrademarksIndex> TrademarksIndex { get; set; }
    }
}
