//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckChanges.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSigns
    {
        public string Sign { get; set; }
        public string FullDescription { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> ToShow { get; set; }
        public string FullDescriptionRussian { get; set; }
        public string FullDescriptionTM { get; set; }
        public string FullDescriptionTMRussian { get; set; }
        public Nullable<bool> ShowSign { get; set; }
        public string ToSubDivisions { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public int idDS { get; set; }
    }
}
