//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckChanges.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventions
    {
        public string Our_case { get; set; }
        public string Serial_number { get; set; }
        public string Patent_number { get; set; }
        public Nullable<int> Attorney_ID { get; set; }
        public Nullable<int> Agent_ID { get; set; }
        public Nullable<int> Applicant_ID { get; set; }
        public Nullable<int> Applicant_ID_2 { get; set; }
        public Nullable<int> Applicant_ID_3 { get; set; }
        public Nullable<int> Applicant_ID_4 { get; set; }
        public Nullable<int> Applicant_ID_5 { get; set; }
        public Nullable<int> Applicant_ID_6 { get; set; }
        public string Inventions_title_National_ { get; set; }
        public string TitleFilingLanguage { get; set; }
        public string Inventions_title_Russian_ { get; set; }
        public string Office_ref { get; set; }
        public string Agent_ref { get; set; }
        public string Their_ref { get; set; }
        public Nullable<System.DateTime> Filing_date { get; set; }
        public Nullable<System.DateTime> Filed_in_DP { get; set; }
        public Nullable<System.DateTime> C1_priority_date { get; set; }
        public string C1_priority_num { get; set; }
        public Nullable<System.DateTime> C2_priority_date { get; set; }
        public string C2_priority_num { get; set; }
        public Nullable<System.DateTime> C3_priority_date { get; set; }
        public string C3_priority_num { get; set; }
        public Nullable<short> Claims { get; set; }
        public string Other_prioryties { get; set; }
        public Nullable<int> Author_ID_1 { get; set; }
        public Nullable<int> Author_ID_2 { get; set; }
        public Nullable<int> Author_ID_3 { get; set; }
        public Nullable<int> Author_ID_4 { get; set; }
        public Nullable<int> Author_ID_5 { get; set; }
        public Nullable<int> Author_ID_6 { get; set; }
        public Nullable<int> Author_ID_7 { get; set; }
        public Nullable<int> Author_ID_8 { get; set; }
        public Nullable<int> Author_ID_9 { get; set; }
        public Nullable<int> Author_ID_10 { get; set; }
        public Nullable<bool> isDivisional { get; set; }
        public string PCT_number { get; set; }
        public Nullable<System.DateTime> PCT_date { get; set; }
        public string IPC_number { get; set; }
        public Nullable<int> Contact_to { get; set; }
        public Nullable<System.DateTime> Patent_date { get; set; }
        public string Remarks { get; set; }
        public string StatusID { get; set; }
        public Nullable<double> Archives_ { get; set; }
        public Nullable<bool> Closed { get; set; }
        public string ForeignPatents { get; set; }
        public Nullable<System.DateTime> WO_date { get; set; }
        public string WO_number { get; set; }
        public Nullable<short> StageID { get; set; }
        public Nullable<int> StageID_old { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> User_Cr_Date { get; set; }
        public string Last_User { get; set; }
        public Nullable<System.DateTime> Last_User_Date { get; set; }
        public string Claims_list { get; set; }
        public Nullable<short> Claims_Total { get; set; }
        public Nullable<int> Text { get; set; }
        public Nullable<int> Text_notEngl { get; set; }
        public Nullable<short> Text_discount { get; set; }
        public Nullable<short> Full_discount { get; set; }
        public Nullable<bool> Search_Report { get; set; }
        public Nullable<short> Appl_type { get; set; }
        public string OurCaseID_save { get; set; }
        public Nullable<int> ExaminerID { get; set; }
        public Nullable<int> Applicants_type { get; set; }
        public Nullable<bool> RichCountryResidents { get; set; }
        public Nullable<int> Text_base_UA_RU { get; set; }
        public Nullable<short> PublPages { get; set; }
        public string Filing_number { get; set; }
        public Nullable<short> Ann_Y { get; set; }
        public Nullable<System.DateTime> Next_Y { get; set; }
        public Nullable<System.DateTime> Date4m { get; set; }
        public Nullable<System.DateTime> Examination_date { get; set; }
        public Nullable<int> SpecificationID { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<bool> IsPhysical { get; set; }
        public Nullable<int> PhysicalAttorneyID { get; set; }
        public Nullable<bool> IsInternationalFiling { get; set; }
        public string QueryBound { get; set; }
        public Nullable<bool> NotToShow { get; set; }
        public string NewRefNum { get; set; }
        public string ParentApplication { get; set; }
        public Nullable<System.DateTime> DivisionalDate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string IPCoster_Prj { get; set; }
        public Nullable<int> FilingLanguageId { get; set; }
        public Nullable<int> NationalLanguageId { get; set; }
        public bool Validation { get; set; }
        public bool AttorneyWorkspace { get; set; }
        public bool CNCN { get; set; }
        public Nullable<bool> PrReadChk { get; set; }
        public Nullable<int> PrReadWords { get; set; }
        public Nullable<bool> chQualControl { get; set; }
        public bool LimitedPatent { get; set; }
        public bool GuarantePayment { get; set; }
        public Nullable<int> RATypeId { get; set; }
        public string FinanceInstrForCase { get; set; }
    
        public virtual About_partner About_partner { get; set; }
    }
}
