//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckChanges.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL
    {
        public int RegNo { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Получатель_Отправитель { get; set; }
        public string Наш_номер { get; set; }
        public string Вид_корреспонденции { get; set; }
        public string Содержание { get; set; }
        public string Приложение { get; set; }
        public string File { get; set; }
        public string Исполнитель { get; set; }
        public string Creator { get; set; }
        public Nullable<bool> IN_OUT { get; set; }
        public string AgentRef { get; set; }
        public Nullable<int> Входящий { get; set; }
        public Nullable<System.DateTime> Принят { get; set; }
        public string ControlFlag { get; set; }
        public Nullable<System.DateTime> ConfirmReceive { get; set; }
        public Nullable<System.DateTime> ConfirmFiling { get; set; }
        public Nullable<System.DateTime> ConfirmReturn { get; set; }
        public string File_Reply { get; set; }
        public Nullable<int> Urgency { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<bool> Urgent { get; set; }
        public string File_Reply2 { get; set; }
        public string CourierType { get; set; }
        public Nullable<System.DateTime> CourierDate { get; set; }
        public Nullable<bool> ToShow { get; set; }
        public Nullable<bool> ShowReply { get; set; }
        public Nullable<System.DateTime> File_Storage { get; set; }
        public Nullable<System.DateTime> DateFiling { get; set; }
        public Nullable<System.DateTime> TempDateFiling { get; set; }
        public Nullable<System.DateTime> TimeDF { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> NotToShow { get; set; }
        public Nullable<System.DateTime> SentFromKh { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> IgnoreDescription { get; set; }
        public Nullable<int> ParentRegNo { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string ToCountry { get; set; }
        public Nullable<System.DateTime> DeliveredToRUbyCurier { get; set; }
        public Nullable<int> FirmPlat { get; set; }
    }
}
