//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckChanges.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nemo_freshEntities : DbContext
    {
        public nemo_freshEntities()
            : base("name=nemo_freshEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About_partner> About_partner { get; set; }
        public virtual DbSet<Inventions> Inventions { get; set; }
        public virtual DbSet<MAIL> MAIL { get; set; }
        public virtual DbSet<PartnerZoneCriteria> PartnerZoneCriteria { get; set; }
        public virtual DbSet<Shedule> Shedule { get; set; }
        public virtual DbSet<ScheduleClientChangesLog> ScheduleClientChangesLog { get; set; }
        public virtual DbSet<MailChangedLog> MailChangedLog { get; set; }
        public virtual DbSet<DocumentFolders> DocumentFolders { get; set; }
        public virtual DbSet<DocumentSigns> DocumentSigns { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersCheckChanges> UsersCheckChanges { get; set; }
        public virtual DbSet<TrademarksIndex> TrademarksIndex { get; set; }
    }
}
