//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckChanges.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrademarksIndex
    {
        public string Our_case { get; set; }
        public Nullable<int> Attorney_ID { get; set; }
        public Nullable<int> Agent_ID { get; set; }
        public Nullable<int> Applicant_ID { get; set; }
        public string Wordmark { get; set; }
        public string Trademark_colors { get; set; }
        public Nullable<bool> IsColor { get; set; }
        public string Goods_list { get; set; }
        public string Classes { get; set; }
        public Nullable<byte> Number_of_classes { get; set; }
        public string Their_ref { get; set; }
        public string Office_ref { get; set; }
        public string Agent_ref { get; set; }
        public Nullable<int> USSR_number { get; set; }
        public Nullable<System.DateTime> Filing_date { get; set; }
        public Nullable<System.DateTime> C1_priority_date { get; set; }
        public string C1_priority_num { get; set; }
        public string International_number { get; set; }
        public Nullable<System.DateTime> International_date { get; set; }
        public string Serial_number { get; set; }
        public string Certificate_number { get; set; }
        public Nullable<int> Contact_to { get; set; }
        public Nullable<System.DateTime> Patent_date { get; set; }
        public string TM_font { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> Archives_ { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<int> ExaminerID { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> User_Cr_Date { get; set; }
        public string Last_User { get; set; }
        public Nullable<System.DateTime> Last_User_Date { get; set; }
        public string Our_ref { get; set; }
        public string StatusID { get; set; }
        public Nullable<System.DateTime> Renewal_date { get; set; }
        public Nullable<bool> Print { get; set; }
        public Nullable<short> ApplicationID { get; set; }
        public string TrademarkDescription { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<bool> IsPhysical { get; set; }
        public Nullable<int> PhysicalAttorneyID { get; set; }
        public string QueryBound { get; set; }
        public Nullable<bool> NotToShow { get; set; }
        public string NewRefNum { get; set; }
        public Nullable<bool> AcceleratedExamination { get; set; }
        public Nullable<bool> Efiling { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string ImageName { get; set; }
        public string IPCoster_Prj { get; set; }
        public Nullable<bool> IPCosterOurRoleInPrj { get; set; }
        public Nullable<bool> CNCN { get; set; }
        public string ClassRemarks { get; set; }
        public string RusColorName { get; set; }
        public string EngColorName { get; set; }
        public string OrderNumberFromSite { get; set; }
        public int BasicLanguageGoodsAndServices { get; set; }
        public int TargetLanguageGoodsAndServices { get; set; }
        public string FinanceInstrForCase { get; set; }
    
        public virtual About_partner About_partner { get; set; }
    }
}
