//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckChanges.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersCheckChanges
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public bool IsInv { get; set; }
        public bool IsTM { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
